name: ROS2 Tracing CPP Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    release:
    types:
      - published

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up LTTNG
        run: |
          sudo apt-add-repository ppa:lttng/stable-2.13 -y
          sudo apt-get update
          sudo apt-get install -y lttng-tools lttng-modules-dkms liblttng-ust-dev
      
      - name: Build Babeltrace2 from Source
        run: |
          mkdir -p external && cd external
          curl -L https://www.efficios.com/files/babeltrace/babeltrace2-2.0.6.tar.bz2 -o babeltrace.tar.bz2
          tar -xvf babeltrace.tar.bz2 && cd babeltrace2-*
          BABELTRACE_DEV_MODE=1 BABELTRACE_MINIMAL_LOG_LEVEL=TRACE ./configure --disable-debug-info
          make -j$(nproc)
          sudo make install

      - name: Build Plugin
        run: |
          mkdir -p build && cd build
          cmake ..
          make -j$(nproc)

      - name: Verify Plugins Built Successfully
        run: |
          if [ ! -f build/plugins/libros2_tracing_cpp.so ]; then
            echo "Plugin build failed!" && exit 1
          fi

  create-release:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    needs: build-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Upload Plugin to Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: build/plugins/libros2_tracing_cpp.so
          tag: ${{ github.ref }}
          allowUpdates: true